### ISSUE TITLE
String Localization and Unicode support

### ISSUE THREAD

**Issue by seanpaultaylor** [gameplay3d/GamePlay#173]
I would like to have a way that developers simply only have to change all their existing string and simply replace them as aliases for new localized versions that are pulled in at run-time based on the devices locale and loaded from the associated matching file holding that specific language. If none are found it falls back to english or their string ids.
This is a pretty standard approach.

**Comment by terry8yu** [comment]
What status is the feature(Unicode support) now?
If possible, send me @xwaffelx has done for this, I want to try to finish it.

**Comment by xwaffelx** [comment]
@terry8yu I'm afraid I don't have that source any more.

**Comment by terry8yu** [comment]
So, this feature now was killed, is it?

**Comment by rcmaniac25** [comment]
Sounds like it. If you'd like to work on it, give it a go.

**Comment by reven86** [comment]
Well, the way I did localization was by changing all text API to use wchar_t * instead of char *. And then doing utf-8 to wide char conversion on client side, I mean in game project. So, there is no additional string selection logic in the Gameplay3D, just pure drawing and handling of widestrings. And there is no additional dependencies on third-party libraries for gameplay3d. It works on every platform I've tested.

This of course breaks compatibility for any existing Gameplay3D project, because API has changed, as well as Lua support for setText methods for Labels, Buttons and Fonts. If this is desired implementation I can open a Pull Request.

**Comment by coderedefine** [comment]
@reven86 i think Unicode text support is very important for gameplay3d, :) , i think i need it now.....

**Comment by coderedefine** [comment]
@seanpaultaylor i found version 1.8.0 from @reven86's tag, that's version was supported unicode string. i think can merge his code in to version 3.0 ,need your help:)

**Comment by rcmaniac25** [comment]
*time delay*

You may need to work on that yourself. Similar to @reven86's fork of it, you'd need to fork and update 3.0. @seanpaultaylor is often so busy that they can only spend a short time doing work, and he has already made it apparent that it should use ICU and most likely without switching to wchar_t, I doubt he will put the effort in to make an incompatible version of GP3D.

I find it strange that nobody has been able to complete this. I'll add to my already large todo list to take a look at localization support, based on @xwaffelx's code, but won't commit to working on it given it's almost cursed nature of never being completed.
