### ISSUE TITLE
Changing text in a center-aligned label doesn't properly update layout

### ISSUE THREAD

**Issue by rgngl** [gameplay3d/GamePlay#1750]
When I have a form like below, the initial layout looks fine. If I change the text of the label and cause the width of the label change, the position of the label still stays same.
```
form gameLevel
{
    layout = LAYOUT_ABSOLUTE
    style = Empty
    consumeInputEvents = false
    batchingEnabled = true

    container countDown {
        visible = false
        consumeInputEvents = false
        autoWidth = true
        autoHeight = true
        alignment = ALIGN_VCENTER_HCENTER

        label countDownLabel
        {
            alignment = ALIGN_VCENTER_HCENTER
            text = 0
            fontSize = 80
        }
    }
}
```

**Comment by reven86** [comment]
I had same issue and have fixed it in my fork. This happened due to the 'dirty' flag was not properly resolved on parents with custom layout or non-top-left alignment when child was updated. There also was another issue when margin of children controls was not taken into account. I can sum up all my UI commits and open a pull request.

**Comment by rgngl** [comment]
Cool!

**Comment by reven86** [comment]
I've just noticed that your container has visible flag set to false. Why is that? That could be a reason why it's not updated nor its children.

**Comment by rgngl** [comment]
Hmm, it's invisible in the beginning then I set it visible and update some text(like a countdown timer at the beginning of the level).
