### ISSUE TITLE
Android and iOS build is broken

### ISSUE THREAD

**Issue by rgngl** [gameplay3d/GamePlay#1758]
See FrameBuffer.cpp:203 and 204

**Comment by rgngl** [comment]
@jimduchek

**Comment by jimduchek** [comment]
Oh, hell.  Those functions have been around since OpenGL 2.0, I didn't consider ES might not have them.    See https://github.com/jimduchek/GamePlay/commit/b063b3a02f91124faacfad84e384dcb59bed12ae

I think it should work.  Grabbing the android ndk now to test before i make a pull request on it though.
