### ISSUE TITLE
Emscripten support

### ISSUE THREAD

**Issue by VinnyVicious** [gameplay3d/GamePlay#1762]
https://github.com/kripken/emscripten as a platform would be nice.

**Comment by zakki** [comment]
Graphics is almost compatible.
Sounds and input device handling are needed.

http://zakki.github.io/GamePlay/
https://github.com/zakki/GamePlay/commit/44690e9ef04ac6f5cdab50b30beab242307c818f

**Comment by rgngl** [comment]
Wow, haven't tried building but this looks nice. Apparently emscripten supports OpenAL out-of-the box. What's missing with the sound handling?

**Comment by zakki** [comment]
I have not looked deep, but no std::thread nor pthread.

**Comment by VinnyVicious** [comment]
Does gameplay3d depend on threads?

**Comment by zakki** [comment]
`AudioController` uses `std::thread` and `std::this_thread::sleep_for`

**Comment by VinnyVicious** [comment]
Emscripten apparently supports it now: https://github.com/kripken/emscripten/issues/2456

**Comment by reven86** [comment]
I've managed to compile sample-browser under Emscripten (thanks @zakki for the platform code) and it works well, except the camera in WaterSample, but it may be due to a lot of changes in my fork. Here you can try it yourself, just give it a time to load all 35MB of assets (it may take~15min to load from github.io): http://reven86.github.io/sample-browser.html or download it and try localy from [here](https://drive.google.com/file/d/0B0w1xHJVc1SeY1d3Ykd6Rzl2YWs/view?usp=sharing). When trying localy it's better to start local server (python -m SimpleHTTPServer 8080) and then open http://localhost:8080/sample-browser.html, because Chrome doesn't allow downloading assets using file:// protocol.

There were several issues during the compilation process, I describe them here, so anyone can build it as well.
1. gameplay dependencies should be linked separately, not as one libgameplay-deps.a library, because emscripten can't load that library.
2. at least bullet and vorbis/ogg libraries should be built as shared libraries (.so) to avoid name collisions during linking phase
3. if using WebGL-friendly subset of OpenGL (the default option), the MeshBatch's logic should be changed to bind vertex buffer prior to call glDrawArrays.
4. creating depthstencil renderbuffers should also be made different way, because WebGL introduces new format and attachment parameter to glRenderbufferStorage and glFramebufferRenderbuffer functions

**Comment by seanpaultaylor** [comment]
Very cool.
