### ISSUE TITLE
PhysX instead of Bullet? Why?

### ISSUE THREAD

**Issue by VinnyVicious** [gameplay3d/GamePlay#1836]
The NextGen version will, supposedly, have PhysX instead of Bullet. This is terrible, due to the licensing of PhysX, which is proprietary software. Is there any special reason why this is being changed?

**Comment by xthydra** [comment]
where did you get that reference that the nextgen version will support physX instead of bullet?

**Comment by JVene** [comment]
I'm not associated with any developer of Gameplay, just a visiting user, but I thought about this myself.

PhysX is no longer licensed like it once was. It was included with the UE4 engine, and was made free, open source with a few caveats.

PhysX was heavily oriented towards GPU (or GPU like PhysX card) computed physics, but was expanded at some point following NVidia's acquisition to work both as a CPU/GPU engine (either or both). The free version is for the CPU implementation only. That's actually good for mobile, since on mobile devices the GPU is busy enough just rendering. 

Bullet has been good, with quirks, got better over time, and for a while PhysX was behind. In recent versions (most specifically 3.3), however, PhysX has pulled out ahead. All engines have quirks; it's the nature of the concept of simulating physics with such real time constraints, but PhysX 3.3 has demonstrated a strong tendency to remain stable with high performance and efficiency beyond what Bullet has been doing by comparison. Look at the source of both, it seems clear to me that PhysX is clearer to read through, easier to understand. 

Bullet has a much better series of demonstration/sample code. It's hard to know what to expect from PhysX from a fresh download of the package by itself. If you examine UE4, however, you'll get a sense of what PhysX can do. There is much to like.
