### ISSUE TITLE
nextgen status

### ISSUE THREAD

**Issue by futagoza** [gameplay3d/GamePlay#1838]
Just checked in today wondering what the status of [GamePlay-nextgen](https://github.com/gameplay3d/GamePlay-nextgen) was, but found that the repository is gone. What happened?

**Comment by seanpaultaylor** [comment]
Since I will be doing a major overhaul, I will be working directly in my fork-ed branch instead. 
It makes it easier for me for merging over code that I want to preserve, etc.

Editor update:
I will no longer be using Qt for the editor though. I did some some initial prototypes and was not as impressed with the cross-platform experience and the nuisances of anything custom for widgets whilst also theming. 
The new prototype of the editor I am working on will use a themed version if imgui or something else similar that is immediate mode. 
The editor is compiled in Debug builds on desktops when a special shortcut is pressed it become visible/active.
