### ISSUE TITLE
EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by ahmsayat** [gameplay3d/GamePlay#1841]
In function 

```C++
Texture* Texture::create(Format format, unsigned int width, unsigned int height, const unsigned char* data, bool generateMipmaps) {
```

this line 
```C++
    GL_ASSERT( glGenTextures(1, &textureId) );
```

gives  EXC_BAD_ACCESS 

Only when threads trying to call  
```C++
Texture * textur = Texture::create(image, false); 
```

normal call don't break. Why?

**Comment by zejji** [comment]
As described [here](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_threading/opengl_threading.html), "Every time your application calls an OpenGL function, OpenGL implicitly looks up the context associated with the current thread and modifies the state or objects associated with that context."

Since **OpenGL contexts cannot be shared between threads** (see [here](http://stackoverflow.com/questions/11097170/multithreaded-rendering-on-opengl)), your call to glGenTextures from a thread other than the main thread will break. For a suggested solution, you could try the approach suggested [here](http://higherorderfun.com/blog/2011/05/26/multi-thread-opengl-texture-loading/), but be aware that it would require modification of the GamePlay core code and you would have to be very comfortable with both C++ threading and the OpenGL API.

**Comment by ahmsayat** [comment]
Thanks @zejji for your reply. Yes, OpenGL contexts or functions starting with gl better called from main. I will modify my program to delegate fetching network resources via thread; but, once threads finish I will render the textures returned via a function in the main thread.
